Feature voice
LaughLax/icarus5 pull request #130
Opened 2022-02-28 05:38 UTC by richardfrost2

Resolves #118 

Creates `/voice lock [@users]`, `/voice streamlock [@users]`, and `/voice unlock`, as well as the channel management.

I did not port the music playing or soundboard features as they've been disabled for longer than the time I've been in LDSG. They can be ported later if desired.

Feedback is currently in text format but it shouldn't be too hard to use an embed instead.

2022-02-28 07:04 UTC, Maldor commented
Commits have commented out the suspended role. Use of the suspension role is to deny users who have the role the ability to connect to voice channels. This is primarily used when they need to not connect to voice channels because of violations of the code of conduct, but do not need to have a full mute issued. This state is likely to be temporary and is used as a probation for those that don't have issues in text channels but do have issues in a voice channel.

This is less likely to happen but including a small check to make sure there are at least 2 voice channels available for use at any given time would help address an odd situation in which a reboot of Icarus is done while at the same time a user joins a channel, thus creating a situation where only 1 channel is available. Such a check need not run every time this code is run, but could be either:
1. Done on startup
2. Done as an async when other state checking code is done
Regardless, this check is considered as having no priority and is purely a QoL feature.

btw, I'm not meant to be authoritive in any way and anything here is merely additional information and can likely be safely disregarded :)

2022-03-07 01:50 UTC, LaughLax requested changes
I haven't tested this myself yet; I'd like to do that before I approve this PR. Skimming over it, it looks pretty good. I've left a few comments on things that need adjustment.

As well, please merge the latest changes into this branch so that it's ready to be merged into master.

2022-03-07 01:50 UTC, LaughLax commented on modules/voice.js
> +function random(iter) {
This function is available in `utils.js` as `u.rand(iter)`.

2022-03-07 01:50 UTC, LaughLax commented on modules/voice.js
> +    await ensureVoiceChannelsOpen(interaction.client);
Let's give this its own subcommand instead of running after `lock`, `unlock`, or `streamlock`

2022-03-07 01:50 UTC, LaughLax commented on registry/voice.json
> +        "description": "Locks your voice channel to new members.",
Let's adjust the tense for these: "Lock ..." etc.

2022-04-19 02:26 UTC, LaughLax approved these changes

2022-04-19 02:27 UTC, merged