Migrate verse.js -> gospel.js
LaughLax/icarus5 pull request #139
Opened 2022-03-19 06:08 UTC by richardfrost2

Fulfills #117. I implemented the slash command found in gospel.json (now slashGospel.json).

I added `rss-parser` as a dependency to get news from the Church Newsroom. 

One idea of how to improve this further:
* Maybe the news command could show multiple news items with fields. Discord allows markdown-style links in embeds sent as interaction responses.

2022-04-19 01:47 UTC, LaughLax requested changes
Three small changes needed. Two are noted in comments. The other is to please adjust `register-commands.js` to register `slashGospel.json`.

2022-04-19 01:47 UTC, LaughLax commented on modules/gospel.js
> +    const versesList = verses.split(",");
Let's adjust this to also allow semicolons.
```suggestion
    const versesList = verses.split(/[,;]/);
```

2022-04-19 01:47 UTC, LaughLax commented on modules/gospel.js
> +    if ((date.getMonth() == 9 && (date.getDate() - date.getDay()) >= 0) || date.getMonth() > 9) week -= 1;
This was necessary in 2020, but now results in the wrong week. These lines can be commented out (in case they'll be needed in future years).

2022-04-30 00:08 UTC, richardfrost2 commented
All right, I think I did what you asked. Let me know if there's anything else you'd like me to do!

2022-05-02 05:32 UTC, LaughLax approved these changes

2022-05-02 05:37 UTC, LaughLax commented
I just realized that this will not fully complete #117 because it won't catch & automatically display verse references in the Gospel category.

In the meantime, I'm going to go ahead and merge/deploy this PR. Thanks for the good work @richardfrost2!

2022-05-02 05:37 UTC, merged