Replace and repost announced posts with invites
LaughLax/icarus5 pull request #166
Opened 2022-08-14 20:04 UTC by BobbyTheCatfish

Resolves #149

2022-08-18 04:31 UTC, LaughLax requested changes
Looks good; I've suggested a couple minor changes that will keep the code a bit less verbose. Accept those and we'll get this merge going

2022-08-18 04:31 UTC, LaughLax commented on modules/01-filter.js
> +            return msg.channel.send({ embeds: msg.embeds, attachments: msg.attachments });
```suggestion
            const embeds = [u.embed({ author: msg.author }).setDescription(msg.content)].concat(msg.embeds);
            return msg.channel.send({ embeds: embeds, attachments: msg.attachments });
```

2022-08-18 04:31 UTC, LaughLax commented on modules/01-filter.js
> +          return msg.channel.send({ embeds: msg.embeds, attachments: msg.attachments });
```suggestion
          const embeds = [u.embed({ author: msg.author }).setDescription(msg.content)].concat(msg.embeds);
          return msg.channel.send({ embeds: embeds, attachments: msg.attachments });
```

2022-08-18 17:30 UTC, BobbyTheCatfish commented
The changes have been committed

2022-09-06 03:09 UTC, LaughLax approved these changes

2022-09-06 07:37 UTC, merged